# NUMPY 

Two difference between numpy arrays and python lists are efficient data storage and vector operations.

In [3]:
import numpy as np

In [2]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.random.randint(0,50,10)

array([13, 35,  2, 18, 49, 35, 40,  6, 22,  7])

In [4]:
np.random.normal(10,8,(4,4)) #mean, stddev, shape

array([[-2.9865845 ,  0.55949274, 11.80728899,  9.71555974],
       [ 2.62053404,  5.36223704,  5.70810531, 11.52622655],
       [13.97944855, 11.41702961,  8.12772515, 10.88205146],
       [ 1.82024188, -0.42775542,  8.05805856, -1.92215354]])

## ARRAY ATTRIBUTES and METHODS

In [5]:
dices = np.random.randint(1,7,10)
dices

array([4, 3, 2, 4, 6, 4, 1, 5, 6, 3])

In [7]:
dices.ndim

1

In [8]:
dices.size

10

In [9]:
dices.shape

(10,)

In [10]:
dices.dtype

dtype('int32')

In [11]:
dices.reshape(5,2)

array([[4, 3],
       [2, 4],
       [6, 4],
       [1, 5],
       [6, 3]])

## ARRAY INDEXING

In [14]:
dices = np.random.randint(1,7,(2,10))
dices

array([[2, 3, 5, 3, 5, 1, 6, 4, 4, 1],
       [6, 1, 1, 1, 4, 6, 1, 5, 1, 3]])

In [15]:
dices[1,0]

6

In [17]:
dices[0,0] = 4.35 #fixed-type
dices

array([[4, 3, 5, 3, 5, 1, 6, 4, 4, 1],
       [6, 1, 1, 1, 4, 6, 1, 5, 1, 3]])

In [29]:
dices[1][[x for x in np.arange(0,10,2)]] #fancy-index

array([6, 1, 4, 1, 1])

In [33]:
dices[0][dices[0] < 3] #conditional indexing

array([1, 1])

np.where()

In [4]:
arr = np.array([0,2,0,1,1,0,0,0,3,0,8,0,6,0,8,0,0,0,0])

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [6]:
arr

array([0, 2, 0, 1, 1, 0, 0, 0, 3, 0, 8, 0, 6, 0, 8, 0, 0, 0, 0])